---

- name: Clean dnf changes
  when: ansible_facts.os_family | lower == "redhat"
  block:
    - name: Remove repo files
      become: true
      loop: "{{ repo_setup_yum[ansible_facts.distribution | lower][ansible_facts.distribution_major_version] | dict2items(key_name='id', value_name='param') }}"
      loop_control:
        loop_var: repo
        label: "{{ repo.id }}"
      ansible.builtin.yum_repository:
        name: "{{ repo.id }}"
        state: absent
      register: repo_removal

    - name: Clean dnf cache
      become: true
      ansible.builtin.command:
        cmd: dnf clean all
      register: dnf_clean_result
      changed_when: dnf_clean_result.rc == 0

    - name: Update dnf metadata cache
      become: true
      ansible.builtin.dnf:
        update_cache: true

- name: Remove pip config
  become: true
  ansible.builtin.file:
    path: "{{ pip_global_config_path }}"
    state: "absent"

...
