---

- name: Configure local mirror
  when: repo_setup_local_mirror | length  > 0
  block:
    - name: Include repo files logic
      ansible.builtin.include_tasks:
        file: "{{ ansible_facts.os_family | lower }}.yml"

- name: Configure pip registries
  become: true
  when: pip_repo_setup_online_mirror is ansible.builtin.string
  ansible.builtin.template:
    src: "pip.conf.j2"
    dest: "{{ pip_global_config_path }}"
    mode: "0644"
    owner: "root"
    group: "root"

...
