---

- name: Validate rhel setup
  when: ansible_facts.os_family | lower == "redhat"
  block:
    - name: Get enabled repos
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          dnf repolist --enabled | awk 'NR > 1 {print $1}'
        executable: /bin/bash
      changed_when: false
      register: enabled_repos_result

    - name: Test enabled repos
      loop: "{{ repo_setup_yum[ansible_facts.distribution | lower][ansible_facts.distribution_major_version] | dict2items(key_name='id', value_name='param') }}"
      loop_control:
        loop_var: repo
        label: "{{ repo.id }}"
      ansible.builtin.assert:
        that:
          - repo_setup_prefix | lower ~ '-' ~ repo.id in enabled_repos_result.stdout_lines
        fail_msg: "Failed to find {{ repo_setup_prefix | lower ~ '-' ~ repo.id }}"
        quiet: true

    - name: Test package install
      become: true
      ansible.builtin.package:
        name:
          - htop
          - btop
          - curl-minimal
          - unzip
        state: present

...
